services:
  - type: web
    name: vision-senas-backend
    env: python
    plan: free
    buildCommand: pip install -r app/requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
    healthCheckPath: /
